language: node_js

node_js:
  - 5.5.0

compiler: clang-3.6

env:
  - CXX=clang-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test

    packages:
      - clang-3.6
      - g++-4.8

before_install:
  - npm install -g babel-cli

after_success: npm run cov
